package oracle.medical.app.model.bc.entity.settings;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 15 12:18:31 EET 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CampEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CampId,
        Camp;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CAMPID = AttributesEnum.CampId.index();
    public static final int CAMP = AttributesEnum.Camp.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CampEOImpl() {
    }

    /**
     * Gets the attribute value for CampId, using the alias name CampId.
     * @return the value of CampId
     */
    public Number getCampId() {
        return (Number) getAttributeInternal(CAMPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CampId.
     * @param value value to set the CampId
     */
    public void setCampId(Number value) {
        setAttributeInternal(CAMPID, value);
    }

    /**
     * Gets the attribute value for Camp, using the alias name Camp.
     * @return the value of Camp
     */
    public String getCamp() {
        return (String) getAttributeInternal(CAMP);
    }

    /**
     * Sets <code>value</code> as the attribute value for Camp.
     * @param value value to set the Camp
     */
    public void setCamp(String value) {
        setAttributeInternal(CAMP, value);
    }

    /**
     * @param campId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number campId) {
        return new Key(new Object[] { campId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("oracle.medical.app.model.bc.entity.settings.CampEO");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation == DML_INSERT) {
            SequenceImpl seq = new SequenceImpl("CAMP_SEQ", this.getDBTransaction());
            Number camp_id = seq.getSequenceNumber();
            this.setCampId(camp_id);
        }
        super.doDML(operation, e);
    }
}

