package oracle.medical.app.model.bc.entity.settings;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 03 18:08:22 EET 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MilitaryServiceEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        MilitaryServiceId,
        MilitaryServiceType;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int MILITARYSERVICEID = AttributesEnum.MilitaryServiceId.index();
    public static final int MILITARYSERVICETYPE = AttributesEnum.MilitaryServiceType.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MilitaryServiceEOImpl() {
    }

    /**
     * Gets the attribute value for MilitaryServiceId, using the alias name MilitaryServiceId.
     * @return the value of MilitaryServiceId
     */
    public Number getMilitaryServiceId() {
        return (Number) getAttributeInternal(MILITARYSERVICEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MilitaryServiceId.
     * @param value value to set the MilitaryServiceId
     */
    public void setMilitaryServiceId(Number value) {
        setAttributeInternal(MILITARYSERVICEID, value);
    }

    /**
     * Gets the attribute value for MilitaryServiceType, using the alias name MilitaryServiceType.
     * @return the value of MilitaryServiceType
     */
    public String getMilitaryServiceType() {
        return (String) getAttributeInternal(MILITARYSERVICETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for MilitaryServiceType.
     * @param value value to set the MilitaryServiceType
     */
    public void setMilitaryServiceType(String value) {
        setAttributeInternal(MILITARYSERVICETYPE, value);
    }

    /**
     * @param militaryServiceId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number militaryServiceId) {
        return new Key(new Object[] { militaryServiceId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("oracle.medical.app.model.bc.entity.settings.MilitaryServiceEO");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation == DML_INSERT) {
            SequenceImpl seq = new SequenceImpl("MILITARY_SERVICE_SEQ", this.getDBTransaction());
            Number service_id = seq.getSequenceNumber();
            this.setMilitaryServiceId(service_id);
        }
        super.doDML(operation, e);
    }
}

