package oracle.medical.app.model.bc.entity.settings;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 03 18:06:45 EET 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OresTypeEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        OresTypeId,
        OresType;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ORESTYPEID = AttributesEnum.OresTypeId.index();
    public static final int ORESTYPE = AttributesEnum.OresType.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OresTypeEOImpl() {
    }

    /**
     * Gets the attribute value for OresTypeId, using the alias name OresTypeId.
     * @return the value of OresTypeId
     */
    public Number getOresTypeId() {
        return (Number) getAttributeInternal(ORESTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OresTypeId.
     * @param value value to set the OresTypeId
     */
    public void setOresTypeId(Number value) {
        setAttributeInternal(ORESTYPEID, value);
    }

    /**
     * Gets the attribute value for OresType, using the alias name OresType.
     * @return the value of OresType
     */
    public String getOresType() {
        return (String) getAttributeInternal(ORESTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OresType.
     * @param value value to set the OresType
     */
    public void setOresType(String value) {
        setAttributeInternal(ORESTYPE, value);
    }

    /**
     * @param oresTypeId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number oresTypeId) {
        return new Key(new Object[] { oresTypeId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("oracle.medical.app.model.bc.entity.settings.OresTypeEO");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation == DML_INSERT) {
            SequenceImpl seq = new SequenceImpl("ORES_TYPE_SEQ", this.getDBTransaction());
            Number type_id = seq.getSequenceNumber();
            this.setOresTypeId(type_id);
        }
        super.doDML(operation, e);
    }
}

