package oracle.medical.app.model.bc.entity.settings;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 16 15:22:48 EET 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class QualificationEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        QualificationId,
        Qualification,
        Specialization;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int QUALIFICATIONID = AttributesEnum.QualificationId.index();
    public static final int QUALIFICATION = AttributesEnum.Qualification.index();
    public static final int SPECIALIZATION = AttributesEnum.Specialization.index();

    /**
     * This is the default constructor (do not remove).
     */
    public QualificationEOImpl() {
    }

    /**
     * Gets the attribute value for QualificationId, using the alias name QualificationId.
     * @return the value of QualificationId
     */
    public Number getQualificationId() {
        return (Number) getAttributeInternal(QUALIFICATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for QualificationId.
     * @param value value to set the QualificationId
     */
    public void setQualificationId(Number value) {
        setAttributeInternal(QUALIFICATIONID, value);
    }

    /**
     * Gets the attribute value for Qualification, using the alias name Qualification.
     * @return the value of Qualification
     */
    public String getQualification() {
        return (String) getAttributeInternal(QUALIFICATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Qualification.
     * @param value value to set the Qualification
     */
    public void setQualification(String value) {
        setAttributeInternal(QUALIFICATION, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSpecialization() {
        return (RowIterator) getAttributeInternal(SPECIALIZATION);
    }

    /**
     * @param qualificationId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number qualificationId) {
        return new Key(new Object[] { qualificationId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("oracle.medical.app.model.bc.entity.settings.QualificationEO");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation == DML_INSERT) {
            SequenceImpl seq = new SequenceImpl("QUALIFICATION_SEQ", this.getDBTransaction());
            Number qualification_id = seq.getSequenceNumber();
            this.setQualificationId(qualification_id);
        }
        super.doDML(operation, e);
    }
}

