package oracle.medical.app.model.bc.module.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 31 16:58:33 EET 2019
// ---------------------------------------------------------------------
public interface IndividualsAppModuleAM extends ApplicationModule {
    void filterSoldiers();

    void filterSergeants();

    void filterOfficers();

    void terminateSoldier();
}

