package oracle.medical.app.model.bc.module.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 18 19:52:11 PDT 2019
// ---------------------------------------------------------------------
public interface ProductsAppModuleAM extends ApplicationModule {
    void approveAddRequests(oracle.jbo.domain.Number requestId, oracle.jbo.domain.Number productId,
                            oracle.jbo.domain.Number quantity);

    void approveDiscountRequests(oracle.jbo.domain.Number requestId, oracle.jbo.domain.Number productId,
                                 oracle.jbo.domain.Number quantity);

    void deleteChild(oracle.jbo.domain.Number productId);

    void deleteRequests(oracle.jbo.domain.Number productId);

    void nonAcceptedAddRequests();

    void setActiveProducts();

    void setWaitingProducts();

    void nonAcceptedDiscountRequests();

    Boolean discountAllowed(oracle.jbo.domain.Number oreId, oracle.jbo.domain.Number quantity);

    void returnAddNewAttrDefault(oracle.jbo.domain.Number productId);

    void setMainActiveProduct();

    void filterAddQuantity();

    void filterDiscountQuantity();
}

