package oracle.medical.app.model.bc.module.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Mar 17 10:38:30 EET 2019
// ---------------------------------------------------------------------
public interface StoreAppModuleAM extends ApplicationModule {
    void setActiveOre();

    void setWaitingOre();

    void setMainActiveOre();
}

