package oracle.medical.app.model.bc.module.common;

import java.util.Date;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 19 15:03:56 EET 2019
// ---------------------------------------------------------------------
public interface StoreActionsAppModuleAM extends ApplicationModule {
    void deleteChild(oracle.jbo.domain.Number oreId);

    void filterAddQuantity();

    void filterDiscountQuantity();

    void filterAddReport();

    void filterDiscountReport();

    void deleteReport(oracle.jbo.domain.Number oreId);

    void deleteRequests(oracle.jbo.domain.Number oreId);


    void approveDiscountRequests(oracle.jbo.domain.Number requestId, oracle.jbo.domain.Number oreId,
                                 oracle.jbo.domain.Number quantity);

    Boolean discountAllowed(oracle.jbo.domain.Number oreId, oracle.jbo.domain.Number quantity);

    void returnAddNewAttrDefault(oracle.jbo.domain.Number oreId);

    void approveAddRequests(oracle.jbo.domain.Number requestId, oracle.jbo.domain.Number oreId,
                            oracle.jbo.domain.Number quantity);
}

