package oracle.medical.app.model.bc.module.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 18 12:38:45 EET 2019
// ---------------------------------------------------------------------
public interface UsersAppModuleAM extends ApplicationModule {
    boolean checkLogin(String email, String password);


}

