package oracle.medical.app.model.bc.dropdownlist;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 19 21:31:32 EET 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IndividualsDropDownVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public IndividualsDropDownVOImpl() {
    }
}

